### ISSUE TITLE
Tkinter can't display multilingua

### ISSUE THREAD

**Issue by LuPow132** [rakky33/GPTVtuber-2.0#1]
When someone chat in and when it display it on tkinter
the problem is if the text is something that tkinter can't show it will crash.

Maybe need to block the other languages.

I don't wanna cut out GUI fr

Here the error log:
Traceback (most recent call last):
  File "D:\AI PYTHON\Python\Lib\tkinter__init.py", line 1948, in call
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\AI PYTHON\Python\Lib\tkinter__init.py", line 861, in callit
    func(*args)
  File "d:\AI PYTHON\GPTVtuber2.0\run.py", line 128, in ChatConnected
    appendTextFile("Conversation_saver.txt",f"\n{message}")
  File "d:\AI PYTHON\GPTVtuber2.0\run.py", line 29, in appendTextFile
    f.write(input)
  File "D:\AI PYTHON\Python\Lib\encodings\cp874.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 15-18: character maps to <undefined>

**Comment by LuPow132** [comment]
Just kidding the problem is with read and wirte defualt function python we need to use UTF-8 as encoding since it has more  widely used encoding that supports a wide range of characters thx to chatGPT lol:
