### ISSUE TITLE
Normal read wirte and overwrite function from python can't use with other languages character?

### ISSUE THREAD

**Issue by LuPow132** [rakky33/GPTVtuber-2.0#2]
According to many place it happend to be the same 

will fix it some day lol

Here the error log:
Traceback (most recent call last):
  File "D:\AI PYTHON\Python\Lib\tkinter__init.py", line 1948, in call
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\AI PYTHON\Python\Lib\tkinter__init.py", line 861, in callit
    func(*args)
  File "d:\AI PYTHON\GPTVtuber2.0\run.py", line 128, in ChatConnected
    appendTextFile("Conversation_saver.txt",f"\n{message}")
  File "d:\AI PYTHON\GPTVtuber2.0\run.py", line 29, in appendTextFile
    f.write(input)
  File "D:\AI PYTHON\Python\Lib\encodings\cp874.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 15-18: character maps to <undefined>

**Comment by LuPow132** [comment]
Change the code from
def appendTextFile(filename, input):
    with open(filename, mode='a') as f:
        f.write(input)
to
def appendTextFile(filename, input):
    with open(filename, mode='a', encoding='utf-8') as f:
        f.write(input)
we add encoding as utf-8 so it support more languages
